doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from Acme\Migrations
    # as migrations classes should NOT be autoloaded
    'DoctrineMigrations': '%kernel.project_dir%/src/Infrastructure/Shared/Migration'

  # available in version >= 1.2. Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
  organize_migrations: BY_YEAR_AND_MONTH
