doctrine:
  orm:
    mappings:
      Order:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Order/Doctrine/Orm/Mapping'
        prefix: 'Acme\Domain\Order'
        alias: Order
