doctrine:
  dbal:
    types:
      email: Acme\Infrastructure\Shared\Doctrine\EmailType
      hashed_password: Acme\Infrastructure\Shared\Doctrine\HashedPasswordType
      phone_number: Acme\Infrastructure\Shared\Doctrine\PhoneNumberType
    mapping_types:
      email: string
      hashed_password: string
      phone_number: string
